SET FOREIGN_KEY_CHECKS =0;
SET SQL_SAFE_UPDATES = 0;

DROP TABLE IF EXISTS `TOY`;

CREATE TABLE `TOY` (
	`TOY_SNO`	VARCHAR(255) PRIMARY KEY	NOT NULL,
	`NAME`	VARCHAR(255)	NULL,
	`IMAGE`	VARCHAR(255)	NULL,
	`MATERIAL`	VARCHAR(255)	NULL,
	`EFFECT`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `FEED`;

CREATE TABLE `FEED` (
	`FEED_SNO`	VARCHAR(255) PRIMARY KEY	NOT NULL,
	`GRADE_NO`	INT UNSIGNED	NOT NULL,
	`PARTICLE_NO`	INT UNSIGNED	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL,
	`IMAGE`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `SNACK`;

CREATE TABLE `SNACK` (
	`SNACK_SNO`	VARCHAR(255) PRIMARY KEY	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL,
	`IMAGE`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `MATERIAL`;

CREATE TABLE `MATERIAL` (
	`MATERIAL_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `FEED_MATERIAL`;

CREATE TABLE `FEED_MATERIAL` (
	`FEED_MATERIAL_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`FEED_SNO`	VARCHAR(255)	NOT NULL,
	`MATERIAL_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
	`USERS_SNO`	VARCHAR(255) PRIMARY KEY	NOT NULL,
	`KAKAO_ID`	VARCHAR(255)	NOT NULL,
	`EMAIL`	VARCHAR(100)	NULL,
	`NAME`	VARCHAR(50)	NOT NULL,
	`PHONE`	VARCHAR(50)	NOT NULL,
	`ADDRESS`	VARCHAR(100)	NOT NULL
);

DROP TABLE IF EXISTS `EFFECT`;

CREATE TABLE `EFFECT` (
	`EFFECT_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `GRADE`;

CREATE TABLE `GRADE` (
	`GRADE_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `PARTICLE`;

CREATE TABLE `PARTICLE` (
	`PARTICLE_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `TARGET`;

CREATE TABLE `TARGET` (
	`TARGET_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `FEED_EFFECT`;

CREATE TABLE `FEED_EFFECT` (
	`FEED_EFFECT_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`FEED_SNO`	VARCHAR(255)	NOT NULL,
	`EFFECT_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `FEED_TARGET`;

CREATE TABLE `FEED_TARGET` (
	`FEED_TARGET_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`FEED_SNO`	VARCHAR(255)	NOT NULL,
	`TARGET_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `ITEM_REVIEW`;

CREATE TABLE `ITEM_REVIEW` (
	`ITEM_REVIEW_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`USERS_SNO`	VARCHAR(255)	NOT NULL,
	`PURCHASE_NO`	INT UNSIGNED	NOT NULL,
	`PET_SNO`	VARCHAR(255)	NOT NULL,
	`ITEM_SNO`	VARCHAR(255)	NULL,
	`RATE`	INT UNSIGNED	NOT NULL,
	`CONTENT`	TEXT	NULL,
	`IMAGE`	VARCHAR(255)	NULL,
    `CREATED_AT` DATETIME null default now()
);

DROP TABLE IF EXISTS `SUBSCRIBTION_HISTORY`;

CREATE TABLE `SUBSCRIBTION_HISTORY` (
	`SUBSCRIBTION_HISTORY_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`PET_SNO`	VARCHAR(255)	NOT NULL,
	`USERS_SNO`	VARCHAR(255)	NOT NULL,
	`START_DATE`	DATE	NOT NULL,
	`END_DATE`	DATE	NOT NULL,
	`AUTO_PAYMENT_FLAG`	INT UNSIGNED	NOT NULL	DEFAULT 0
);

DROP TABLE IF EXISTS `SUBSCRIBTION`;

CREATE TABLE `SUBSCRIBTION` (
	`SUBSCRIBTION_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`NAME`	VARCHAR(255)	NOT NULL,
	`DESCRIBTION`	TEXT	NULL,
	`PRICE`	INT UNSIGNED	NOT NULL,
	`IMAGE`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `SNACK_MATERIAL`;

CREATE TABLE `SNACK_MATERIAL` (
	`SNACK_MATERIAL_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SNACK_SNO`	VARCHAR(255)	NOT NULL,
	`MATERIAL_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `SNACK_EFFECT`;

CREATE TABLE `SNACK_EFFECT` (
	`SNACK_EFFECT_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SNACK_SNO`	VARCHAR(255)	NOT NULL,
	`EFFECT_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `SNACK_TARGET`;

CREATE TABLE `SNACK_TARGET` (
	`SNACK_TARGET_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`TARGET_NO`	INT UNSIGNED	NOT NULL,
	`SNACK_SNO`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `PET_MATERIAL`;

CREATE TABLE `PET_MATERIAL` (
	`PET_MATERIAL_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`PET_SNO`	VARCHAR(255)	NOT NULL,
	`MATERIAL_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `PET_EFFECT`;

CREATE TABLE `PET_EFFECT` (
	`PET_EFFECT_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`PET_SNO`	VARCHAR(255)	NOT NULL,
	`EFFECT_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `PURCHASE_PLAN`;

CREATE TABLE `PURCHASE_PLAN` (
	`PURCHASE_PLAN_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`PET_SNO`	VARCHAR(255)	NOT NULL,
	`USERS_SNO`	VARCHAR(255)	NOT NULL,
	`ITEM_SNO`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `USERS_LOG`;

CREATE TABLE `USERS_LOG` (
	`USERS_LOG_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`USERS_SNO`	VARCHAR(255)	NOT NULL,
	`USERS_CREATED_AT`	DATETIME	NOT NULL,
	`USERS_UPDATED_AT`	DATETIME	NULL,
	`USERS_DELETED_AT`	DATETIME	NULL
);

DROP TABLE IF EXISTS `PURCHASE`;

CREATE TABLE `PURCHASE` (
	`PURCHASE_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SUBSCRIBTION_HISTORY_NO`	INT UNSIGNED	NOT NULL,
	`ITEM_SNO`	VARCHAR(255)	NULL,
	`REFUND_DATE`	DATE	NULL
);

DROP TABLE IF EXISTS `SERVICE_REVIEW`;

CREATE TABLE `SERVICE_REVIEW` (
	`SERVICE_REVIEW_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`USERS_SNO`	VARCHAR(255)	NOT NULL,
	`SUBSCRIBTION_HISTORY_NO`	INT UNSIGNED	NOT NULL,
    `REG_DATE` DATE NULL default(current_date),
	`RATE`	INT UNSIGNED	NOT NULL,
	`CONTENT`	TEXT	NULL,
	`IMAGE`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `PET`;

CREATE TABLE `PET` (
	`PET_SNO`	VARCHAR(255) PRIMARY KEY	NOT NULL,
	`USERS_SNO`	VARCHAR(255)	NOT NULL,
	`TARGET_NO`	INT UNSIGNED	NOT NULL,
	`NAME`	VARCHAR(50)	NOT NULL,
	`BIRTH`	DATE	NOT NULL,
	`FAT`	INT UNSIGNED	NOT NULL,
	`IMAGE`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `PRODUCT_TYPE`;

CREATE TABLE `PRODUCT_TYPE` (
	`PRODUCT_TYPE_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`NAME`	VARCHAR(50)	NOT NULL
);

DROP TABLE IF EXISTS `SUBSCRIBTION_PRODUCT_TYPE`;

CREATE TABLE `SUBSCRIBTION_PRODUCT_TYPE` (
	`SUBSCRIBTION_PRODUCT_TYPE_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`PRODUCT_TYPE_NO`	INT UNSIGNED	NOT NULL,
	`SUBSCRIBTION_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `CopyOfUSERS_LOG`;


DROP TABLE IF EXISTS `SUBSCRIBTION_HISTORY_SUBSCRIBTION`;

CREATE TABLE `SUBSCRIBTION_HISTORY_SUBSCRIBTION` (
	`SUBSCRIBTION_HISTORY_SUBSCRIBTION_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`SUBSCRIBTION_HISTORY_NO`	INT UNSIGNED	NOT NULL,
	`SUBSCRIBTION_NO`	INT UNSIGNED	NOT NULL
);

DROP TABLE IF EXISTS `PAYMENT`;

CREATE TABLE `PAYMENT` (
	`PAYMENT_NO`	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT	NOT NULL
);

ALTER TABLE `FEED` ADD CONSTRAINT `FK_GRADE_TO_FEED_1` FOREIGN KEY (
	`GRADE_NO`
)
REFERENCES `GRADE` (
	`GRADE_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FEED` ADD CONSTRAINT `FK_PARTICLE_TO_FEED_1` FOREIGN KEY (
	`PARTICLE_NO`
)
REFERENCES `PARTICLE` (
	`PARTICLE_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FEED_MATERIAL` ADD CONSTRAINT `FK_FEED_TO_FEED_MATERIAL_1` FOREIGN KEY (
	`FEED_SNO`
)
REFERENCES `FEED` (
	`FEED_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FEED_MATERIAL` ADD CONSTRAINT `FK_MATERIAL_TO_FEED_MATERIAL_1` FOREIGN KEY (
	`MATERIAL_NO`
)
REFERENCES `MATERIAL` (
	`MATERIAL_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FEED_EFFECT` ADD CONSTRAINT `FK_FEED_TO_FEED_EFFECT_1` FOREIGN KEY (
	`FEED_SNO`
)
REFERENCES `FEED` (
	`FEED_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FEED_EFFECT` ADD CONSTRAINT `FK_EFFECT_TO_FEED_EFFECT_1` FOREIGN KEY (
	`EFFECT_NO`
)
REFERENCES `EFFECT` (
	`EFFECT_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FEED_TARGET` ADD CONSTRAINT `FK_FEED_TO_FEED_TARGET_1` FOREIGN KEY (
	`FEED_SNO`
)
REFERENCES `FEED` (
	`FEED_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FEED_TARGET` ADD CONSTRAINT `FK_TARGET_TO_FEED_TARGET_1` FOREIGN KEY (
	`TARGET_NO`
)
REFERENCES `TARGET` (
	`TARGET_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ITEM_REVIEW` ADD CONSTRAINT `FK_USERS_TO_ITEM_REVIEW_1` FOREIGN KEY (
	`USERS_SNO`
)
REFERENCES `USERS` (
	`USERS_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ITEM_REVIEW` ADD CONSTRAINT `FK_PURCHASE_TO_ITEM_REVIEW_1` FOREIGN KEY (
	`PURCHASE_NO`
)
REFERENCES `PURCHASE` (
	`PURCHASE_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;



ALTER TABLE `ITEM_REVIEW` ADD CONSTRAINT `FK_PET_TO_ITEM_REVIEW_1` FOREIGN KEY (
	`PET_SNO`
)
REFERENCES `PET` (
	`PET_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SUBSCRIBTION_HISTORY` ADD CONSTRAINT `FK_PET_TO_SUBSCRIBTION_HISTORY_1` FOREIGN KEY (
	`PET_SNO`
)
REFERENCES `PET` (
	`PET_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SUBSCRIBTION_HISTORY` ADD CONSTRAINT `FK_USERS_TO_SUBSCRIBTION_HISTORY_1` FOREIGN KEY (
	`USERS_SNO`
)
REFERENCES `USERS` (
	`USERS_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SNACK_MATERIAL` ADD CONSTRAINT `FK_SNACK_TO_SNACK_MATERIAL_1` FOREIGN KEY (
	`SNACK_SNO`
)
REFERENCES `SNACK` (
	`SNACK_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SNACK_MATERIAL` ADD CONSTRAINT `FK_MATERIAL_TO_SNACK_MATERIAL_1` FOREIGN KEY (
	`MATERIAL_NO`
)
REFERENCES `MATERIAL` (
	`MATERIAL_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SNACK_EFFECT` ADD CONSTRAINT `FK_SNACK_TO_SNACK_EFFECT_1` FOREIGN KEY (
	`SNACK_SNO`
)
REFERENCES `SNACK` (
	`SNACK_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SNACK_EFFECT` ADD CONSTRAINT `FK_EFFECT_TO_SNACK_EFFECT_1` FOREIGN KEY (
	`EFFECT_NO`
)
REFERENCES `EFFECT` (
	`EFFECT_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SNACK_TARGET` ADD CONSTRAINT `FK_TARGET_TO_SNACK_TARGET_1` FOREIGN KEY (
	`TARGET_NO`
)
REFERENCES `TARGET` (
	`TARGET_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SNACK_TARGET` ADD CONSTRAINT `FK_SNACK_TO_SNACK_TARGET_1` FOREIGN KEY (
	`SNACK_SNO`
)
REFERENCES `SNACK` (
	`SNACK_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PET_MATERIAL` ADD CONSTRAINT `FK_PET_TO_PET_MATERIAL_1` FOREIGN KEY (
	`PET_SNO`
)
REFERENCES `PET` (
	`PET_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PET_MATERIAL` ADD CONSTRAINT `FK_MATERIAL_TO_PET_MATERIAL_1` FOREIGN KEY (
	`MATERIAL_NO`
)
REFERENCES `MATERIAL` (
	`MATERIAL_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PET_EFFECT` ADD CONSTRAINT `FK_PET_TO_PET_EFFECT_1` FOREIGN KEY (
	`PET_SNO`
)
REFERENCES `PET` (
	`PET_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PET_EFFECT` ADD CONSTRAINT `FK_EFFECT_TO_PET_EFFECT_1` FOREIGN KEY (
	`EFFECT_NO`
)
REFERENCES `EFFECT` (
	`EFFECT_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PURCHASE_PLAN` ADD CONSTRAINT `FK_PET_TO_PURCHASE_PLAN_1` FOREIGN KEY (
	`PET_SNO`
)
REFERENCES `PET` (
	`PET_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PURCHASE_PLAN` ADD CONSTRAINT `FK_USERS_TO_PURCHASE_PLAN_1` FOREIGN KEY (
	`USERS_SNO`
)
REFERENCES `USERS` (
	`USERS_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `USERS_LOG` ADD CONSTRAINT `FK_USERS_TO_USERS_LOG_1` FOREIGN KEY (
	`USERS_SNO`
)
REFERENCES `USERS` (
	`USERS_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PURCHASE` ADD CONSTRAINT `FK_SUBSCRIBTION_HISTORY_TO_PURCHASE_1` FOREIGN KEY (
	`SUBSCRIBTION_HISTORY_NO`
)
REFERENCES `SUBSCRIBTION_HISTORY` (
	`SUBSCRIBTION_HISTORY_NO`
) ON DELETE CASCADE ON UPDATE CASCADE; 

ALTER TABLE `SERVICE_REVIEW` ADD CONSTRAINT `FK_USERS_TO_SERVICE_REVIEW_1` FOREIGN KEY (
	`USERS_SNO`
)
REFERENCES `USERS` (
	`USERS_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SERVICE_REVIEW` ADD CONSTRAINT `FK_SUBSCRIBTION_HISTORY_TO_SERVICE_REVIEW_1` FOREIGN KEY (
	`SUBSCRIBTION_HISTORY_NO`
)
REFERENCES `SUBSCRIBTION_HISTORY` (
	`SUBSCRIBTION_HISTORY_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PET` ADD CONSTRAINT `FK_USERS_TO_PET_1` FOREIGN KEY (
	`USERS_SNO`
)
REFERENCES `USERS` (
	`USERS_SNO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PET` ADD CONSTRAINT `FK_TARGET_TO_PET_1` FOREIGN KEY (
	`TARGET_NO`
)
REFERENCES `TARGET` (
	`TARGET_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SUBSCRIBTION_PRODUCT_TYPE` ADD CONSTRAINT `FK_PRODUCT_TYPE_TO_SUBSCRIBTION_PRODUCT_TYPE_1` FOREIGN KEY (
	`PRODUCT_TYPE_NO`
)
REFERENCES `PRODUCT_TYPE` (
	`PRODUCT_TYPE_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SUBSCRIBTION_PRODUCT_TYPE` ADD CONSTRAINT `FK_SUBSCRIBTION_TO_SUBSCRIBTION_PRODUCT_TYPE_1` FOREIGN KEY (
	`SUBSCRIBTION_NO`
)
REFERENCES `SUBSCRIBTION` (
	`SUBSCRIBTION_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SUBSCRIBTION_HISTORY_SUBSCRIBTION` ADD CONSTRAINT `FK_SUBSCRIBTION_HISTORY_TO_SUBSCRIBTION_HISTORY_SUBSCRIBTION_1` FOREIGN KEY (
	`SUBSCRIBTION_HISTORY_NO`
)
REFERENCES `SUBSCRIBTION_HISTORY` (
	`SUBSCRIBTION_HISTORY_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SUBSCRIBTION_HISTORY_SUBSCRIBTION` ADD CONSTRAINT `FK_SUBSCRIBTION_TO_SUBSCRIBTION_HISTORY_SUBSCRIBTION_1` FOREIGN KEY (
	`SUBSCRIBTION_NO`
)
REFERENCES `SUBSCRIBTION` (
	`SUBSCRIBTION_NO`
) ON DELETE CASCADE ON UPDATE CASCADE;

alter table SUBSCRIBTION auto_increment=100;
alter table PURCHASE auto_increment=100;
alter table `ITEM_REVIEW` modify `PURCHASE_NO` INT UNSIGNED;


CREATE INDEX idx_itemSno ON ITEM_REVIEW ( ITEM_SNO );

insert into SUBSCRIBTION(SUBSCRIBTION_NO, NAME, DESCRIBTION, PRICE) values
(1,"Basic Package","사료 1",30000),
(2,"Play Package","간식 3, 장난감 2",70000),
(3,"All In One Package","사료 1, 간식 3, 장난감 2",100000),
(4,"DalDal Package","사료 1, 간식 3",60000),
(5,"Toy Package","사료 1, 장난감 2",70000),
(6,"Light All Package","사료 1, 간식 1, 장난감 1",60000);


SET FOREIGN_KEY_CHECKS =1;